# Generated by Django 5.1.4 on 2024-12-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena_app', '0002_sessions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField()),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateTimeField()),
                ('location', models.CharField(max_length=50)),
                ('fav_sport', models.CharField(max_length=100)),
            ],
        ),
    ]
