# Generated by Django 5.1.4 on 2024-12-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena_app', '0003_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='gender',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
    ]
