# Generated by Django 5.1.4 on 2024-12-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena_app', '0008_alter_booking_sessionid_alter_booking_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='slots_taken',
            field=models.IntegerField(default=0),
        ),
    ]
